### ISSUE TITLE
Including library into CasperJs

### ISSUE THREAD

**Issue by gekannt** [boo1ean/casual#32]
I tried using library by just including it as require('casual')

I get the following error in response:

![6300111528b901b9630b9115_28-01-2016-23 53 55_b901](https://cloud.githubusercontent.com/assets/1280194/12658556/c7fa4e2c-c61a-11e5-864d-89c12a38ad6f.png)

I tried to look for meaning of __dirname but didn't find where it was defined.

What am I doing wrong?

**Comment by gekannt** [comment]
it looks like it's problem of casperjs

**Comment by boo1ean** [comment]
[__dirname](https://nodejs.org/docs/latest/api/globals.html#globals_dirname) is standart node global variable.

Currently `casual` supports node runtime only, because of usage of node specific stuff

**Comment by boo1ean** [comment]
You can check this fork [casual-browserify](https://github.com/Klowner/casual-browserify). It's aimed to work on client side.
