### ISSUE TITLE
Error after a fresh install: 'exists` is not defined

### ISSUE THREAD

**Issue by woniesong92** [boo1ean/casual#43]
After a fresh install, I get the following error:

```
WARNING in ./~/casual/src/casual.js
Critical dependencies:
6:9-26 the request of a dependency is an expression
 @ ./~/casual/src/casual.js 6:9-26
```

So I look at the code below in the source code:

```
var helpers = require('./helpers'),
    exists = require('fs').existsSync;

var safe_require = function(filename) {
    if (exists(filename + '.js')) {
        return require(filename);
    }
    return {};
};
```

and I think I should add `fs` package. After that, I still get the following error:

```
TypeError: exists is not a function
```

**Comment by Klowner** [comment]
How did you install?

**Comment by HriBB** [comment]
I get a similar error. I feel that this is related ...
```
ERROR in ./~/casual/src/casual.js
Module not found: Error: Cannot resolve module 'fs' in /home/bojan/www/react-mdl-selectfield/node_modules/casual/src
resolve module fs
```

node v6.4.0.

**Comment by Klowner** [comment]
React? Looks like you're building front end stuff, you may want to try
https://github.com/Klowner/casual-browserify, it avoids the fs calls by
requiring everything.

**Comment by HriBB** [comment]
Ahh I see it in the docs. Did not scroll down enough. You might want to put that note higher up :)

Thanks for clarifying this @Klowner
