### ISSUE TITLE
How about a UUID?

### ISSUE THREAD

**Issue by bensleveritt** [boo1ean/casual#57]
Maybe nestled with the numbers?

[UUIDs](https://github.com/kelektiv/node-uuid) are cool, but [CUIDs](https://github.com/ericelliott/cuid) are also pretty popular.

**Comment by bensleveritt** [comment]
Or a [tiny, non-dependency variant](https://gist.github.com/jed/982883)

**Comment by boo1ean** [comment]
Contributions are welcomed :)

**Comment by boo1ean** [comment]
better to use non-dependency variant

**Comment by scalder27** [comment]
Hi, great work!

One thing, could you add typescript definition for uuid?

**Comment by kytwb** [comment]
@scalder27 sure, will do.

**Comment by scalder27** [comment]
@kytwb, thanks!
